#define _SOURCE_UNSTABLE___                                                   0x8901
#define _MEASURED_INPUT_HV_CHANGED_                                           0x8902
#define _MEMORY_CHECK_FAILED_                                                 0x8903
#define _INPUT_TIMING_DOUBLE_CHECK___INTERLACE_FLAG_CHANGE_                   0x8904
#define _INPUT_TIMING_H_POLARITY_                                             0x8905
#define _INPUT_TIMING_V_POLARITY_                                             0x8906
#define _INPUT_TIMING_INTERLACE_                                              0x8907
#define _INPUT_TIMING_HFREQ_                                                  0x8908
#define _INPUT_TIMING_HTOTAL_                                                 0x8909
#define _INPUT_TIMING_HSTART_                                                 0x890A
#define _INPUT_TIMING_HWIDTH_                                                 0x890B
#define _INPUT_TIMING_HSYNCWIDTH_                                             0x890C
#define _INPUT_TIMING_VFREQ_                                                  0x890D
#define _INPUT_TIMING_VTOTAL_                                                 0x890E
#define _INPUT_TIMING_VSTART_                                                 0x890F
#define _INPUT_TIMING_VHEIGHT_                                                0x8910
#define _INPUT_TIMING_VSYNCSWIDTH_                                            0x8911
#define _SYSMODERESETSTATE___                                                 0x8912
#define _7__NO_CABLE_SEARCH_5SECS_                                            0x8913
#define _7__SOURCE_JUDGE_HP_CASE_                                             0x8914
#define _7__WUANNE_TEST___SEARCH_INITIAL___3_                                 0x8915
#define _7__BINGO_SWITCH_PORT________                                         0x8918
#define _7__BINGO_EEPROM_FIX_PORT________                                     0x891D
#define _7__SEARCH_FINISH_____________________                                0x891E
#define _7__SWITCH_PORT_WITH_SIGNAL_                                          0x891F
#define _7__SWITCH_PORT_NO_CABLE_                                             0x8920
#define _7__SWITCH_PORT_NO_SIGNAL_                                            0x8921
#define _7__SWITCH_PORT_NO_CABLE_FINISH_                                      0x8922
#define _7_____SEARCHINDEX____                                                0x8923
#define _7__WUZANEE_TEST___SEARCH_TIMES_                                      0x8924
#define _7__BINGO_DEFAUTLT________                                            0x8925
#define _7__BINGO_PRIORITY________                                            0x8926
#define _7__BINGO_EEPROM________                                              0x8927
#define _7__VGA_PORT_INITIAL_                                                 0x8929
#define _7__D0_PORT_TMDS_PORT_INITIAL_                                        0x892A
#define _7__D0_DP_PORT_INITIAL_                                               0x892B
#define _7__D1_PORT_TMDS_PORT_INITIAL_                                        0x892C
#define _7__D1_DP_PORT_INITIAL_                                               0x892D
#define _7__D2_PORT_TMDS_PORT_INITIAL_                                        0x892E
#define _7__D2_PORT_DUAL_DVI_INITIAL_                                         0x892F
#define _7__D3_PORT_TMDS_PORT_INITIAL_                                        0x8930
#define _7__D3_PORT_DUAL_DVI_INITIAL_                                         0x8931
#define _7__D4_PORT_TMDS_PORT_INITIAL_                                        0x8932
#define _7__D4_PORT_DUAL_DVI_INITIAL_                                         0x8933
#define _7__D5_PORT_TMDS_PORT_INITIAL_                                        0x8934
#define _7__D6_DP_PORT_INITIAL_                                               0x8935
#define _7__OSD_SWITCH_PORT_TO______                                          0x8936
#define _0__CABLE_STATUS_CHANAGED_A0_                                         0x8937
#define _0__CABLE_STATUS_CHANGED_D0_                                          0x8938
#define _0__CABLE_STATUS_CHANGED_D1_                                          0x8939
#define _0__CABLE_STATUS_CHANGED_D2_                                          0x893A
#define _0__CABLE_STATUS_CHANGED_D3_                                          0x893B
#define _0__CABLE_STATUS_CHANGED_D4_                                          0x893C
#define _0__CABLE_STATUS_CHANGED_D5_                                          0x893D
#define _0__CABLE_STATUS_CHANGED_D6_                                          0x893E
#define _VGA_MEASURE_MEASURE_INFO_                                            0x893F
