#define _SOURCE_UNSTABLE___                                                   "Source Unstable!!"
#define _MEASURED_INPUT_HV_CHANGED_                                           "Measured Input HV Changed"
#define _MEMORY_CHECK_FAILED_                                                 "Memory Check Failed"
#define _INPUT_TIMING_DOUBLE_CHECK___INTERLACE_FLAG_CHANGE_                   "Input Timing Double Check : Interlace Flag Change"
#define _INPUT_TIMING_H_POLARITY_                                             "Input Timing H Polarity"
#define _INPUT_TIMING_V_POLARITY_                                             "Input Timing V Polarity"
#define _INPUT_TIMING_INTERLACE_                                              "Input Timing InterLace"
#define _INPUT_TIMING_HFREQ_                                                  "Input Timing HFreq"
#define _INPUT_TIMING_HTOTAL_                                                 "Input Timing HTotal"
#define _INPUT_TIMING_HSTART_                                                 "Input Timing HStart"
#define _INPUT_TIMING_HWIDTH_                                                 "Input Timing HWidth"
#define _INPUT_TIMING_HSYNCWIDTH_                                             "Input Timing HSyncWidth"
#define _INPUT_TIMING_VFREQ_                                                  "Input Timing VFreq"
#define _INPUT_TIMING_VTOTAL_                                                 "Input Timing VTotal"
#define _INPUT_TIMING_VSTART_                                                 "Input Timing VStart"
#define _INPUT_TIMING_VHEIGHT_                                                "Input Timing VHeight"
#define _INPUT_TIMING_VSYNCSWIDTH_                                            "Input Timing VSyncSWidth"
#define _SYSMODERESETSTATE___                                                 "SysModeResetState!!"
#define _7__NO_CABLE_SEARCH_5SECS_                                            "7. No Cable Search 5secs"
#define _7__SOURCE_JUDGE_HP_CASE_                                             "7. Source Judge HP Case"
#define _7__WUANNE_TEST___SEARCH_INITIAL___3_                                 "7. wuanne test : Search Initial : 3"
#define _7__BINGO_SWITCH_PORT________                                         "7. Bingo Switch Port!!!!!!!"
#define _7__BINGO_EEPROM_FIX_PORT________                                     "7. Bingo Eeprom Fix Port!!!!!!!"
#define _7__SEARCH_FINISH_____________________                                "7. Search Finish !!!!!!!!!!!!!!!!!!!"
#define _7__SWITCH_PORT_WITH_SIGNAL_                                          "7. Switch Port with Signal"
#define _7__SWITCH_PORT_NO_CABLE_                                             "7. Switch Port No Cable"
#define _7__SWITCH_PORT_NO_SIGNAL_                                            "7. Switch Port No Signal"
#define _7__SWITCH_PORT_NO_CABLE_FINISH_                                      "7. Switch Port No Cable Finish"
#define _7_____SEARCHINDEX____                                                "7. == SearchIndex =="
#define _7__WUZANEE_TEST___SEARCH_TIMES_                                      "7. wuzanee test : Search Times"
#define _7__BINGO_DEFAUTLT________                                            "7. Bingo Defautlt!!!!!!!"
#define _7__BINGO_PRIORITY________                                            "7. Bingo Priority!!!!!!!"
#define _7__BINGO_EEPROM________                                              "7. Bingo Eeprom!!!!!!!"
#define _7__VGA_PORT_INITIAL_                                                 "7. VGA Port Initial"
#define _7__D0_PORT_TMDS_PORT_INITIAL_                                        "7. D0 Port TMDS Port Initial"
#define _7__D0_DP_PORT_INITIAL_                                               "7. D0 DP Port Initial"
#define _7__D1_PORT_TMDS_PORT_INITIAL_                                        "7. D1 Port TMDS Port Initial"
#define _7__D1_DP_PORT_INITIAL_                                               "7. D1 DP Port Initial"
#define _7__D2_PORT_TMDS_PORT_INITIAL_                                        "7. D2 Port TMDS Port Initial"
#define _7__D2_PORT_DUAL_DVI_INITIAL_                                         "7. D2 Port Dual DVI Initial"
#define _7__D3_PORT_TMDS_PORT_INITIAL_                                        "7. D3 Port TMDS Port Initial"
#define _7__D3_PORT_DUAL_DVI_INITIAL_                                         "7. D3 Port Dual DVI Initial"
#define _7__D4_PORT_TMDS_PORT_INITIAL_                                        "7. D4 Port TMDS Port Initial"
#define _7__D4_PORT_DUAL_DVI_INITIAL_                                         "7. D4 Port Dual DVI Initial"
#define _7__D5_PORT_TMDS_PORT_INITIAL_                                        "7. D5 Port TMDS Port Initial"
#define _7__D6_DP_PORT_INITIAL_                                               "7. D6 DP Port Initial"
#define _7__OSD_SWITCH_PORT_TO______                                          "7. OSD Switch Port to --> "
#define _0__CABLE_STATUS_CHANAGED_A0_                                         "0. Cable Status Chanaged A0"
#define _0__CABLE_STATUS_CHANGED_D0_                                          "0. Cable Status Changed D0"
#define _0__CABLE_STATUS_CHANGED_D1_                                          "0. Cable Status Changed D1"
#define _0__CABLE_STATUS_CHANGED_D2_                                          "0. Cable Status Changed D2"
#define _0__CABLE_STATUS_CHANGED_D3_                                          "0. Cable Status Changed D3"
#define _0__CABLE_STATUS_CHANGED_D4_                                          "0. Cable Status Changed D4"
#define _0__CABLE_STATUS_CHANGED_D5_                                          "0. Cable Status Changed D5"
#define _0__CABLE_STATUS_CHANGED_D6_                                          "0. Cable Status Changed D6"
#define _VGA_MEASURE_MEASURE_INFO_                                            "VGA Measure Measure Info"
